JNG-4495 Release judo meta expression psm
BlackBeltTechnology/judo-meta-expression-psm pull request #54
Opened 2023-02-27 16:40 UTC by gaborflorian

2023-02-27 16:41 UTC, noherczeg approved these changes

2023-02-28 09:00 UTC, Madmat8 approved these changes

2023-02-28 21:50 UTC, bencegelei requested changes

2023-02-28 21:50 UTC, bencegelei commented on pom.xml
> +                <version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:34 UTC, gaborflorian commented on pom.xml
> +                <version>1.2.11</version>
Requested by Robert

2023-03-01 09:36 UTC, gaborflorian commented on pom.xml
> +                <version>1.2.11</version>
Requested by Robert

2023-03-01 09:58 UTC, robertcsakany approved these changes

2023-03-01 11:58 UTC, bencegelei approved these changes

2023-03-09 10:21 UTC, merged